import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const appDbSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'full_name', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'cpf', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'birth_date', type: 'string', isOptional: true },
        { name: 'gender', type: 'string', isOptional: true },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'guardians',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'phone', type: 'string' },
        { name: 'relationship', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'is_deleted', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'safety_diary_entries',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'content', type: 'string' },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'entry_date', type: 'number' },
        { name: 'emotion', type: 'string', isOptional: true },
        { name: 'tags', type: 'string' },
        { name: 'images', type: 'string' },
        { name: 'is_private', type: 'boolean' },
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'is_deleted', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'audio_recordings',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'filename', type: 'string' },
        { name: 'local_uri', type: 'string', isOptional: true },
        { name: 'remote_url', type: 'string', isOptional: true },
        { name: 'duration', type: 'number' },
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'is_deleted', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'documents',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'filename', type: 'string' },
        { name: 'local_uri', type: 'string', isOptional: true },
        { name: 'remote_url', type: 'string', isOptional: true },
        { name: 'mime_type', type: 'string' },
        { name: 'size', type: 'number' },
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'is_deleted', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'emergency_alerts',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'message', type: 'string' },
        { name: 'location_lat', type: 'number', isOptional: true },
        { name: 'location_lng', type: 'number', isOptional: true },
        { name: 'guardians_json', type: 'string' },
        { name: 'is_police_emergency', type: 'boolean' },
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string' },
        { name: 'sent_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'entity_type', type: 'string', isIndexed: true },
        { name: 'entity_local_id', type: 'string' },
        { name: 'entity_remote_id', type: 'string', isOptional: true },
        { name: 'operation', type: 'string' },
        { name: 'payload', type: 'string' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'attempts', type: 'number' },
        { name: 'last_attempted_at', type: 'number', isOptional: true },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
})
